# Autogenerated wrapper script for VCDiff_jll for x86_64-apple-darwin
export libvcdcom, libvcddec, libvcdenc

JLLWrappers.@generate_wrapper_header("VCDiff")
JLLWrappers.@declare_library_product(libvcdcom, "@rpath/libvcdcom.0.dylib")
JLLWrappers.@declare_library_product(libvcddec, "@rpath/libvcddec.0.dylib")
JLLWrappers.@declare_library_product(libvcdenc, "@rpath/libvcdenc.0.dylib")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libvcdcom,
        "lib/libvcdcom.0.8.4.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libvcddec,
        "lib/libvcddec.0.8.4.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libvcdenc,
        "lib/libvcdenc.0.8.4.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
